project:
  type: website
  output-dir: docs

website:
  title: "Stephen Pitts SJ"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - publications.qmd
      - workinprogress.qmd
      - datasets.qmd
      - teaching.qmd 
      - education.qmd 
      - fieldwork.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    page-layout: full



