project:
  type: website
  output-dir: docs
  resources: pdf/*.pdf
  render:
    - "*.qmd"

website:
  title: "Stephen Pitts SJ"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: research.qmd
        text: Research
      - href: teaching.qmd
        text: Teaching
      - href: datasets.qmd
        text: Datasets
      - href: community.qmd
        text: Community

format:
  html:
    theme: cosmo
    css: styles.css
    page-layout: full



